Fix bug in fbpython bridge
Summary: I'm pretty certain this is the right fix (since we call `level = level + 1` immediately upon entering `get_vars`).

Test Plan:
```
[tulloch@devgpu012 /data/users/tulloch/fbcode] fbmake runtests
Starting parallel test runs using 60 jobs...
fblualib/python/test:lua_python_test - main...aborted (0s)
_build/dbg/fblualib/python/test/lua_python_test.llar
error listing test cases
stdout:
stderr:
ImportError: numpy.core.multiarray failed to import
Python error: import numpy array module
ImportError: numpy.core.multiarray failed to import

stack traceback:
[C]: at 0x7fe4c6002cf8
[C]: in function 'require'
...st/lua_python_test.llar.linktree/_lua/fb/python/init.lua:11: in main chunk
[C]: in function 'require'
...ree/_lua/fbcode/fblualib/python/test/lua_python_test.lua:13: in main chunk
[C]: in function 'require'
...ualib/python/test/lua_python_test.llar.linktree/_run.lua:1: in main chunk
Finished 1 test cases in 0.33 seconds with a parallelism of 60
Test Run Time:
fblualib/python/test:lua_python_test: 0s
Test Results Summary:
Aborted: 1
main in fblualib/python/test:lua_python_test
Total:   1
0.00% successful
```

Reviewed By: tudorb@fb.com

FB internal diff: D1657909

Tasks: 5539137

Signature: t1:1657909:1415134589:3d087f7b88a38c426e965196cfd8613dec4564dd